# Generated by Django 5.2.1 on 2025-05-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('idbebida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.IntegerField()),
                ('imagen', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idMenu', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMenu', models.CharField(max_length=50)),
                ('detalleMenu', models.CharField(max_length=250)),
                ('precioMenu', models.IntegerField()),
                ('imagenMenu', models.CharField(max_length=1500)),
            ],
        ),
    ]
