# Generated by Django 5.2.1 on 2025-05-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sopas', models.CharField(max_length=150)),
                ('principio', models.CharField(max_length=150)),
                ('carnes', models.CharField(max_length=250)),
                ('bebida', models.CharField(max_length=150)),
                ('imagen', models.CharField(max_length=350)),
            ],
        ),
    ]
