# Generated by Django 5.2.1 on 2025-05-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_almuerzo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Almuerzo',
            new_name='AlmuerzoEjecu',
        ),
    ]
