# Generated by Django 5.2.1 on 2025-05-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_almuerzo_almuerzoejecu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almuerzoejecu',
            name='imagen',
        ),
        migrations.AddField(
            model_name='almuerzoejecu',
            name='imagenBandeja',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='almuerzoejecu',
            name='imagenSopa',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
